//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kahveci
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparis
    {
        public int siparisID { get; set; }
        public int masaID { get; set; }
        public int urunID { get; set; }
        public int personelID { get; set; }
        public int adet { get; set; }
    
        public virtual masa masa { get; set; }
        public virtual personel personel { get; set; }
        public virtual urun urun { get; set; }
    }
}
